version: '3.2'

networks:
    backend-network:
        driver: bridge
    frontend-network:
        driver: bridge

volumes:
    pg-data:
    home-dir:

services:
    &app-service app: &app-service-template
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ./:/app:rw
            - home-dir:/home/user
        hostname: *app-service
        environment:
            DB_HOST: postgres
            DB_PORT: &pg-port 5432
            DB_DATABASE: &pg-db-name app
            DB_USERNAME: &pg-username forge
            DB_PASSWORD: &pg-password secret
            #SCHEDULE_PERIOD: 60
            FPM_PORT: &php-fpm-port 9000
            FPM_USER: "${USER_ID:-1000}"
            FPM_GROUP: "${GROUP_ID:-1000}"
            APP_ENV: dev
            APP_DEBUG: 'true'
            APP_BASE_URL: &app-base-url book24-transaction-api.loc
            APP_URL: http://book24-transaction-api.loc
            HOME: /home/user
        command: keep-alive.sh
        depends_on:
            - postgres
        networks:
            - backend-network

    &php-fpm-service php-fpm:
        <<: *app-service-template
        user: 'root:root'
        restart: always
        hostname: *php-fpm-service
        ports: [*php-fpm-port]
        entrypoint: /fpm-entrypoint.sh
        command: php-fpm --nodaemonize -d "opcache.enable=0" -d "display_startup_errors=On" -d "display_errors=On" -d "error_reporting=E_ALL"
        networks:
            - backend-network
            - frontend-network

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        restart: always
        working_dir: /usr/share/nginx/html
        environment:
            FPM_HOST: *php-fpm-service
            FPM_PORT: *php-fpm-port
            APP_BASE_URL: *app-base-url
            ROOT_DIR: '/app/public' # App path must equals with php-fpm container path
        volumes:
            - ./:/app:ro
        ports: ['80:80']
        depends_on:
            - *php-fpm-service
        networks:
            - frontend-network

    postgres:
        image: postgres:9.6.10-alpine
        restart: always
        environment:
            POSTGRES_DB: *pg-db-name
            POSTGRES_USER: *pg-username
            POSTGRES_PASSWORD: *pg-password
        volumes:
            - pg-data:/var/lib/postgresql/data:rw
        ports: [*pg-port, '15432:5432'] # Port 15432 for connecting from localhost using, for example, data-grip
        networks:
            - backend-network
